
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache.codingbee.net
  resources:
  - mysqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.codingbee.net
  resources:
  - mysqls/finalizers
  verbs:
  - update
- apiGroups:
  - cache.codingbee.net
  resources:
  - mysqls/status
  verbs:
  - get
  - patch
  - update
